version: '3'

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3310:3306"
    restart: unless-stopped
    container_name: pizzashop_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
  nginx:
    image: nginx:latest
    container_name: pizzashop_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - php
  php:
    build: ./
    container_name: pizzashop_php
    volumes:
      - ./:/var/www
      - ./docker/crontasks:/var/crontasks
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: /bin/bash -c "cp /var/crontasks /var/spool/cron/crontabs/root && chown root:root /var/spool/cron/crontabs/root && chmod 0600 /var/spool/cron/crontabs/root && /usr/bin/supervisord -n -c /var/www/docker/supervisord.conf"
    depends_on:
      - db
    links:
      - db:database_host
    restart: unless-stopped
volumes:
  db_data:
